services:
  db:
    container_name: db
    image: postgres:17
    restart: unless-stopped
    shm_size: 128mb
    env_file:
        - configs/envs/db.env
    ports:
      - 5432:5432

  server:
    container_name: presentation-timer
    build:
        context: .
        dockerfile: build/package/Dockerfile.dev
    restart: unless-stopped
    volumes:
      - .:/usr/src/presentation-timer
    env_file:
        - configs/envs/server.env
    ports:
      - 8000:8000
