# @name Get all
GET {{host}}/presentations
###

# @name Get one
GET {{host}}/presentations/35
###

# @name Create
POST {{host}}/presentations

{
    "name": "my presentation"
}
###

# @name Update
PUT {{host}}/presentations/74

{
    "name": "my presentation 2"
}
###

# @name Patch
PATCH {{host}}/presentations/74

{
    "name": "my presentation 2"
}
###

# @name Patch nothing
PATCH {{host}}/presentations/74

{
}
###

# @name Delete
DELETE {{host}}/presentations/70
###
