### Get all
GET {{URL}}/presentations

### Get one
GET {{URL}}/presentations/35

### Create
POST {{URL}}/presentations

{
    "name": "my presentation"
}

### Update
PUT {{URL}}/presentations/74

{
    "name": "my presentation 2"
}

### Patch
PATCH {{URL}}/presentations/74

{
    "name": "my presentation 2"
}

### Patch nothing
PATCH {{URL}}/presentations/74

{
}

### Delete
DELETE {{URL}}/presentations/70
