### Get all
GET {{host}}/presentations

### Get one
GET {{host}}/presentations/35

### Create
POST {{host}}/presentations

{
    "name": "my presentation"
}

### Update
PUT {{host}}/presentations/74

{
    "name": "my presentation 2"
}

### Patch
PATCH {{host}}/presentations/74

{
    "name": "my presentation 2"
}

### Patch nothing
PATCH {{host}}/presentations/74

{
}

### Delete
DELETE {{host}}/presentations/70
