### Get all
GET {{URL}}/presentations/35/sections

### Get one
GET {{URL}}/sections/13

### Create
POST {{URL}}/presentations/35/sections

{
    "name": "my section",
    "duration": 300000000000,
    "position": 1
}

### Update
PUT {{URL}}/sections/17

{
    "name": "my section 2",
    "duration": 600000000000,
    "position": 2
}

### Delete
DELETE {{URL}}/sections/16
